In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

Import

In [19]:
ai_readiness = pd.read_csv("../datasets/ai_readiness.csv")
databank = pd.read_csv("../datasets/databank.csv")
exports_concentration = pd.read_csv("../datasets/exports_concentration.csv")
innovation = pd.read_csv("../datasets/innovation.csv")

Checkings

In [25]:
ai_readiness.head()

,year,country,rank,total_score,government_pillar,technology_sector_pillar,data_infrastructure_pillar,policy_capacity,ai_infrastructure,governance,public_sector_adoption,development_diffusion,resilience
0,2023,United Arab Emirates,18.0,70.42,78.32,56.67,76.28,NaN,NaN,NaN,NaN,NaN,NaN
1,2023,Saudi Arabia,29.0,67.04,78.71,49.59,72.83,NaN,NaN,NaN,NaN,NaN,NaN
2,2023,Qatar,34.0,63.59,69.64,44.31,76.81,NaN,NaN,NaN,NaN,NaN,NaN
3,2023,Oman,50.0,58.94,69.35,37.71,69.76,NaN,NaN,NaN,NaN,NaN,NaN
4,2023,Bahrain,56.0,56.13,57.96,39.24,71.19,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
ai_readiness[ai_readiness["rank"].isnull()]

,year,country,rank,total_score,government_pillar,technology_sector_pillar,data_infrastructure_pillar,policy_capacity,ai_infrastructure,governance,public_sector_adoption,development_diffusion,resilience
6,2024,United Arab Emirates,NaN,75.66,83.89,59.20,83.89,NaN,NaN,NaN,NaN,NaN,NaN
7,2024,Saudi Arabia,NaN,72.36,80.72,52.92,83.43,NaN,NaN,NaN,NaN,NaN,NaN
8,2024,Qatar,NaN,68.22,76.07,46.90,81.69,NaN,NaN,NaN,NaN,NaN,NaN
9,2024,Oman,NaN,62.91,69.61,41.29,77.84,NaN,NaN,NaN,NaN,NaN,NaN
10,2024,Bahrain,NaN,54.33,45.62,37.61,79.76,NaN,NaN,NaN,NaN,NaN,NaN
11,2024,Kuwait,NaN,51.26,46.49,36.93,70.36,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
ai_readiness.tail()

,year,country,rank,total_score,government_pillar,technology_sector_pillar,data_infrastructure_pillar,policy_capacity,ai_infrastructure,governance,public_sector_adoption,development_diffusion,resilience
13,2025,Saudi Arabia,15.0,NaN,NaN,NaN,NaN,92.0,62.93,93.21,88.62,54.48,57.39
14,2025,Qatar,54.0,NaN,NaN,NaN,NaN,80.5,57.95,77.50,62.82,44.54,38.95
15,2025,Oman,61.0,NaN,NaN,NaN,NaN,88.5,47.22,72.00,71.00,40.29,41.09
16,2025,Bahrain,48.0,NaN,NaN,NaN,NaN,46.5,58.04,72.50,83.37,48.50,49.08
17,2025,Kuwait,83.0,NaN,NaN,NaN,NaN,35.0,53.31,52.63,51.43,30.19,38.01

In [22]:
ai_readiness.shape

(18, 13)

In [23]:
ai_readiness.isnull().sum()

year                           0
country                        0
rank                           6
total_score                    6
government_pillar              6
technology_sector_pillar       6
data_infrastructure_pillar     6
policy_capacity               12
ai_infrastructure             12
governance                    12
public_sector_adoption        12
development_diffusion         12
resilience                    12
dtype: int64

In [5]:
databank.head()

,Country Name,Country Code,Series Name,Series Code,1960 [YR1960],1961 [YR1961],1962 [YR1962],1963 [YR1963],1964 [YR1964],1965 [YR1965],...,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
0,Saudi Arabia,SAU,Oil rents (% of GDP),NY.GDP.PETR.RT.ZS,..,..,..,..,..,..,...,2.000518e+01,2.361707e+01,2.808428e+01,2.432958e+01,1.597891e+01,23.6862940574499,..,..,..,..
1,Saudi Arabia,SAU,Fuel exports (% of merchandise exports),TX.VAL.FUEL.ZS.UN,..,..,..,..,..,..,...,7.754982e+01,7.984682e+01,8.099541e+01,8.005311e+01,7.259380e+01,76.6076971781348,82.1937028956426,81.3099851483006,79.3976376511523,..
2,Saudi Arabia,SAU,"Services, value added (% of GDP)",NV.SRV.TOTL.ZS,..,..,..,..,..,..,...,5.355092e+01,5.143366e+01,4.602234e+01,4.906409e+01,5.458750e+01,45.8018349629672,40.2066530479076,44.7549856751834,47.0745603554281,..
3,Saudi Arabia,SAU,"Manufacturing, value added (% of GDP)",NV.IND.MANF.ZS,..,..,..,..,..,..,...,1.353363e+01,1.342075e+01,1.262166e+01,1.286911e+01,1.338616e+01,14.1394021512741,15.1155743681524,15.8916837283563,15.7219406844133,..
4,Saudi Arabia,SAU,GDP (current US$),NY.GDP.MKTP.CD,1748124063.55556,1920811284.22222,2130606531.77778,2207393171.55556,2371808712.88889,2647955557.55556,...,6.892795e+11,7.412661e+11,8.865648e+11,8.888901e+11,7.679512e+11,982661066666.667,1239075200000,1218584533333.33,1239804533333.33,..

In [6]:
databank.tail()

,Country Name,Country Code,Series Name,Series Code,1960 [YR1960],1961 [YR1961],1962 [YR1962],1963 [YR1963],1964 [YR1964],1965 [YR1965],...,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
31,Bahrain,BHR,Fuel exports (% of merchandise exports),TX.VAL.FUEL.ZS.UN,..,..,..,..,..,..,...,4.501732e+01,5.017711e+01,5.332039e+01,4.212821e+01,2.981919e+01,0.0520982100390362,0.0426131887253156,0.252930709797225,0.000371894251415909,..
32,Bahrain,BHR,"Services, value added (% of GDP)",NV.SRV.TOTL.ZS,..,..,..,..,..,..,...,6.071045e+01,5.882661e+01,5.720615e+01,5.639953e+01,5.782307e+01,52.8740707167008,49.2411387955769,51.944952554339,53.1861438651827,..
33,Bahrain,BHR,"Manufacturing, value added (% of GDP)",NV.IND.MANF.ZS,..,..,..,..,..,..,...,1.784165e+01,1.818449e+01,1.717069e+01,1.704070e+01,1.804689e+01,20.528955608,20.9350892016844,20.1297882520386,19.9093728658114,..
34,Bahrain,BHR,GDP (current US$),NY.GDP.MKTP.CD,..,..,..,..,..,..,...,3.388468e+10,3.720481e+10,3.956798e+10,4.044681e+10,3.583763e+10,40840212765.9574,46458191489.3617,46192260638.2979,47109734308.5106,..
35,Bahrain,BHR,GDP per capita (current US$),NY.GDP.PCAP.CD,..,..,..,..,..,..,...,2.380000e+04,2.478477e+04,2.632441e+04,2.725974e+04,2.434284e+04,27147.8083882286,30470.5219276023,29290.1284215098,29653.5682731534,..

In [11]:
databank["Series Name"].unique()

<StringArray>
[                   'Oil rents (% of GDP)',
 'Fuel exports (% of merchandise exports)',
        'Services, value added (% of GDP)',
   'Manufacturing, value added (% of GDP)',
                       'GDP (current US$)',
            'GDP per capita (current US$)']
Length: 6, dtype: str

In [32]:
exports_concentration.shape

(180, 5)

In [31]:
exports_concentration.isna().sum()

Economy_Label                         0
Year                                  0
Concentration_Index_Value             0
Concentration_Index_Footnote          4
Concentration_Index_MissingValue    180
dtype: int64

In [7]:
exports_concentration.head()

,Economy_Label,Year,Concentration_Index_Value,Concentration_Index_Footnote,Concentration_Index_MissingValue
0,Bahrain,1995,0.402,Estimated,NaN
1,Bahrain,1996,0.398,Estimated,NaN
2,Bahrain,1997,0.390,Estimated,NaN
3,Bahrain,1998,0.408,Estimated,NaN
4,Bahrain,1999,0.422,Estimated,NaN

In [8]:
exports_concentration.tail()

,Economy_Label,Year,Concentration_Index_Value,Concentration_Index_Footnote,Concentration_Index_MissingValue
175,United Arab Emirates,2020,0.227,Estimated,NaN
176,United Arab Emirates,2021,0.242,Estimated,NaN
177,United Arab Emirates,2022,0.299,Estimated,NaN
178,United Arab Emirates,2023,0.280,Estimated,NaN
179,United Arab Emirates,2024,0.282,Estimated,NaN

In [9]:
innovation.head()

   year               country  innovation_score  innovation_rank
0  2025  United Arab Emirates         44.154489               30
1  2025          Saudi Arabia         36.044819               46
2  2025                 Qatar         34.561768               48
3  2025                  Oman         28.649098               69
4  2025               Bahrain         30.015766               62

In [10]:
innovation.tail()

   year       country  innovation_score  innovation_rank
1  2025  Saudi Arabia         36.044819               46
2  2025         Qatar         34.561768               48
3  2025          Oman         28.649098               69
4  2025       Bahrain         30.015766               62
5  2025        Kuwait         28.214302               73

Pivot databank set

In [30]:
# World Bank Databank export: wide years → one row per (country, year)

id_cols = ["Country Name", "Country Code", "Series Name", "Series Code"]
year_cols = [c for c in databank.columns if c not in id_cols]

databank_long = databank.melt(
    id_vars=id_cols,
    value_vars=year_cols,
    var_name="year_raw",
    value_name="value",
)

# "1960 [YR1960]" → 1960
databank_long["year"] = (
    databank_long["year_raw"].astype(str).str.extract(r"(\d{4})")[0].astype("Int64")
)

databank_long["value"] = pd.to_numeric(
    databank_long["value"].replace(["..", ""], pd.NA),
    errors="coerce",
)

series_code_to_col = {
    "NY.GDP.PETR.RT.ZS": "oil_rents_gdp",
    "TX.VAL.FUEL.ZS.UN": "fuel_exports_pct",
    "NV.SRV.TOTL.ZS": "services_gdp",
    "NV.IND.MANF.ZS": "manufacturing_gdp",
    "NY.GDP.MKTP.CD": "gdp",
    "NY.GDP.PCAP.CD": "gdp_per_capita",
}

wdi = (
    databank_long[databank_long["Series Code"].isin(series_code_to_col)]
    .assign(variable=lambda d: d["Series Code"].map(series_code_to_col))
    .pivot_table(
        index=["Country Name", "year"],
        columns="variable",
        values="value",
        aggfunc="first",
    )
    .reset_index()
    .rename(columns={"Country Name": "country"})
)

# The pivot above puts the mapped codes into columns across the variables axis;
# There is no longer a "variable" column to drop. Remove that line and just sort:
wdi = wdi.sort_values(["country", "year"])

wdi.head()

variable,country,year,fuel_exports_pct,gdp,gdp_per_capita,manufacturing_gdp,oil_rents_gdp,services_gdp
0,Bahrain,1970,77.872151,3.915774e+08,1741.822454,NaN,NaN,NaN
1,Bahrain,1971,81.414530,4.221816e+08,1829.740705,NaN,NaN,NaN
2,Bahrain,1972,78.281501,5.340812e+08,2205.917004,NaN,NaN,NaN
3,Bahrain,1973,80.622534,7.611325e+08,2981.092531,NaN,NaN,NaN
4,Bahrain,1974,84.476909,1.042177e+09,3873.716291,NaN,NaN,NaN

Renaming columns (especially key columns) before merge

In [33]:
# UNCTAD → merge keys + export concentration
exports_concentration = exports_concentration.rename(
    columns={
        "Economy_Label": "country",
        "Year": "year",
        "Concentration_Index_Value": "export_concentration",
    }
)

# WIPO GII extract
innovation = innovation.rename(
    columns={
        "innovation_score": "innovation_index",
    }
)

# Oxford AI readiness extract
ai_readiness = ai_readiness.rename(
    columns={
        "total_score": "ai_readiness",
        "rank": "ai_readiness_rank",
    }
)

What column to keep?

In [39]:
wdi_cols = [
    "country",
    "year",
    "oil_rents_gdp",
    "fuel_exports_pct",
    "services_gdp",
    "manufacturing_gdp",
    "gdp",
    "gdp_per_capita",
]
wdi = wdi[wdi_cols]

exports_cols = ["country", "year", "export_concentration"]
exports_concentration = exports_concentration[exports_cols]

innovation_cols = ["country", "year", "innovation_index", "innovation_rank"]
innovation = innovation[innovation_cols]

ai_readiness_cols = [
    "country",
    "year",
    "ai_readiness",
    "ai_readiness_rank",
    "government_pillar",
    "technology_sector_pillar",
    "data_infrastructure_pillar",
    "policy_capacity",
    "ai_infrastructure",
    "governance",
    "public_sector_adoption",
    "development_diffusion",
    "resilience",
]
ai_readiness = ai_readiness[ai_readiness_cols]

Merge

In [40]:
ai_readiness.dtypes

country                           str
year                            int64
ai_readiness                  float64
ai_readiness_rank             float64
government_pillar             float64
technology_sector_pillar      float64
data_infrastructure_pillar    float64
policy_capacity               float64
ai_infrastructure             float64
governance                    float64
public_sector_adoption        float64
development_diffusion         float64
resilience                    float64
dtype: object

In [41]:
exports_concentration.dtypes

country                     str
year                      int64
export_concentration    float64
dtype: object

In [42]:
innovation.dtypes

country                 str
year                  int64
innovation_index    float64
innovation_rank       int64
dtype: object

In [43]:
wdi.dtypes

variable
country                  str
year                   Int64
oil_rents_gdp        float64
fuel_exports_pct     float64
services_gdp         float64
manufacturing_gdp    float64
gdp                  float64
gdp_per_capita       float64
dtype: object

In [44]:
wdi["year"] = wdi["year"].astype(int)

In [45]:
wdi["year"].dtype

dtype('int64')

In [ ]:
for name, _df in [
    ("wdi", wdi),
    ("exports_concentration", exports_concentration),
    ("innovation", innovation),
    ("ai_readiness", ai_readiness),
]:
    assert not _df.duplicated(["country", "year"]).any(), f"duplicate keys in {name}"

In [47]:
merged = (
    wdi.merge(exports_concentration, on=["country", "year"], how="outer")
    .merge(innovation, on=["country", "year"], how="outer")
    .merge(ai_readiness, on=["country", "year"], how="outer")
)
merged = merged.sort_values(["country", "year"], kind="mergesort").reset_index(drop=True)
merged.head()

,country,year,oil_rents_gdp,fuel_exports_pct,services_gdp,manufacturing_gdp,gdp,gdp_per_capita,export_concentration,innovation_index,...,ai_readiness_rank,government_pillar,technology_sector_pillar,data_infrastructure_pillar,policy_capacity,ai_infrastructure,governance,public_sector_adoption,development_diffusion,resilience
0,Bahrain,1970,NaN,77.872151,NaN,NaN,3.915774e+08,1741.822454,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bahrain,1971,NaN,81.414530,NaN,NaN,4.221816e+08,1829.740705,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bahrain,1972,NaN,78.281501,NaN,NaN,5.340812e+08,2205.917004,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bahrain,1973,NaN,80.622534,NaN,NaN,7.611325e+08,2981.092531,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bahrain,1974,NaN,84.476909,NaN,NaN,1.042177e+09,3873.716291,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
merged.shape

(364, 22)

In [49]:
col_order = [
    "country",
    "year",
    "oil_rents_gdp",
    "fuel_exports_pct",
    "services_gdp",
    "manufacturing_gdp",
    "export_concentration",
    "gdp",
    "gdp_per_capita",
    "innovation_index",
    "innovation_rank",
    "ai_readiness",
    "ai_readiness_rank",
    "government_pillar",
    "technology_sector_pillar",
    "data_infrastructure_pillar",
    "policy_capacity",
    "ai_infrastructure",
    "governance",
    "public_sector_adoption",
    "development_diffusion",
    "resilience",
]
merged = merged[col_order]
merged.head()

,country,year,oil_rents_gdp,fuel_exports_pct,services_gdp,manufacturing_gdp,export_concentration,gdp,gdp_per_capita,innovation_index,...,ai_readiness_rank,government_pillar,technology_sector_pillar,data_infrastructure_pillar,policy_capacity,ai_infrastructure,governance,public_sector_adoption,development_diffusion,resilience
0,Bahrain,1970,NaN,77.872151,NaN,NaN,NaN,3.915774e+08,1741.822454,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bahrain,1971,NaN,81.414530,NaN,NaN,NaN,4.221816e+08,1829.740705,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bahrain,1972,NaN,78.281501,NaN,NaN,NaN,5.340812e+08,2205.917004,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bahrain,1973,NaN,80.622534,NaN,NaN,NaN,7.611325e+08,2981.092531,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bahrain,1974,NaN,84.476909,NaN,NaN,NaN,1.042177e+09,3873.716291,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
merged.to_csv("../datasets/merged_dataset.csv", index=False)

SQLite — four source tables (`datasets/postoil.db`)

In [51]:
import sqlite3

db_path = "../datasets/postoil.db"

with sqlite3.connect(db_path) as conn:
    wdi.to_sql("wdi_core", conn, if_exists="replace", index=False)
    exports_concentration.to_sql("export_concentration", conn, if_exists="replace", index=False)
    ai_readiness.to_sql("ai_readiness", conn, if_exists="replace", index=False)
    innovation.to_sql("innovation", conn, if_exists="replace", index=False)

    for tbl in ("wdi_core", "export_concentration", "ai_readiness", "innovation"):
        conn.execute(
            f"CREATE INDEX IF NOT EXISTS idx_{tbl}_country_year ON {tbl} (country, year)"
        )

db_path

'../datasets/postoil.db'